### ISSUE TITLE
Investigate models

### ISSUE THREAD

**Issue by LanesGood** [EpiPandit/atlas-arena#4]
The UCDavis team has shared access to the models hosted on the repo https://github.com/PanditPranav/Climate_Models_Arenaviruses.

One of our first steps should be to understand how these models work and should be integrated into the AtlasArena application. We should determine:
- required inputs, and their formats
- expected outputs
- Variables and controls
- Hosting requirements
- etc

I assume that we will want to host these models within the application itself, and run them as a script that can accept user inputs and then generate outputs. 

We will not be building an API or infrastructure for the model per the scope, so we need to ensure that the models can all run within the application.

**Comment by LanesGood** [comment]
@Rub21 @yunica it looks like I can't assign you directly, but this would be a good first issue to investigate

**Comment by geohacker** [comment]
I've added @rub21 and @yunica to this repo. They should have invites as collaborators. We should be able to assign issues one they accept.

> We will not be building an API or infrastructure for the model per the scope, so we need to ensure that the models can all run within the application.

@LanesGood @Rub21 just to clarify — our intention with this [work plan](https://docs.google.com/document/d/1-2xUkwuHjnsq5WNkIwyMEXX48WN6_gnHDeRIB8dEHtk/edit) is to purely host the model results somewhere so the app can visualize. All updates should happen outside the app and update the results on S3 or so that the app refreshes. We aren't intending to integrate the model as part of the application/frontend.

**Comment by Rub21** [comment]
@geohacker 
> All updates should happen outside the app and update the results on S3 or so that the app refreshes. We aren't intending to integrate the model as part of the application/frontend.

Thanks for the clarification, it was a bit confusing to understand the limits we need to work within.
