### ISSUE TITLE
Using Google Spreadsheet API to Request Data from a Spreadsheet in JSON Format

### ISSUE THREAD

**Issue by Rub21** [EpiPandit/atlas-arena#6]
Seems something useful for the application is to use the Google Spreadsheet API, which allows requesting data from a spreadsheet in JSON format, filtered by sheet. Each sheet can contain rows of data for a specific virus, reducing the amount of data we need to request for each virus in the  web app.

I made a copy from the main Spreadsheet, E.g. https://docs.google.com/spreadsheets/d/19ckITJb-qsBRCEjZLxUbIoytVFuKg0zPFhOKB0MqwJk/edit?gid=773385975#gid=773385975

<img width="616" alt="image" src="https://github.com/user-attachments/assets/30315c46-c3f0-4bdc-84de-54195bcde814">

The URL to request data for the Spreadsheet - each sheet would be:

```
https://sheets.googleapis.com/v4/spreadsheets/{SPREADSHEET_ID}/values/{SHEET_NAME}?key={API_KEY}
```
e.g:

- https://sheets.googleapis.com/v4/spreadsheets/19ckITJb-qsBRCEjZLxUbIoytVFuKg0zPFhOKB0MqwJk/values/guanarito_virus?key=API_KEY

- https://sheets.googleapis.com/v4/spreadsheets/19ckITJb-qsBRCEjZLxUbIoytVFuKg0zPFhOKB0MqwJk/values/machupo_virus?key=API_KEY

Results: 

<img width="1089" alt="image" src="https://github.com/user-attachments/assets/76259e05-409c-46f5-834d-85c71166a20d">

With this workflow, it will be easy for the UC Davis team to add more datasets. Additionally, we can include a new column for TIFs in Mapbox, which will contain the tileset_id.

cc. @yunica @LanesGood @geohacker

**Comment by LanesGood** [comment]
@Rub21 sounds good. Do you think this is easier than organizing the data in a github folder tree structure?

My main thought is that the frontend should have a limited set of columns to select from for the selection of each parameter. I imagine you'll want to think about how to set those columns from a config file, probably locally within the app, so that there is no need to fetch a list of options. EX: there are three viruses; if the frontend requests info related to a virus, it should have no risk of misspellings, and there would also need to be a way for the UC Davis team to update both the spreadsheet and the local config to add new data.
